# SPDX-FileCopyrightText: 2026 Luke Galea
# SPDX-License-Identifier: MIT

# Ensures the test ETS tables exist for test doubles.
:ets.new(:ash_bpmn_test_calls, [:set, :public, :named_table])

# Storage up the test database (creates it if missing).
AshBpmn.TestRepo.__adapter__().storage_up(AshBpmn.TestRepo.config())

# Start the repo (creates the connection pool).
{:ok, _} = AshBpmn.TestRepo.start_link()

# Run migrations — uses priv/test_repo/migrations generated by ash_postgres.
# If the migration directory has no files yet (first run), this is a safe no-op.
migration_path = Path.expand("priv/test_repo/migrations")

if File.dir?(migration_path) do
  Ecto.Migrator.run(
    AshBpmn.TestRepo,
    migration_path,
    :up,
    all: true
  )
end

# Sandbox mode for test isolation.
Ecto.Adapters.SQL.Sandbox.mode(AshBpmn.TestRepo, :manual)

ExUnit.start()
