name: Elixir CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  ash-ci:
    uses: ash-project/ash/.github/workflows/ash-ci.yml@main
    permissions:
      contents: write
      security-events: write
      pages: write
      id-token: write
    with:
      postgres: true
      postgres-version: "16"
      ash_postgres: false
      ecto_postgres: false
      tenants: false
      sobelow: false
      changelog-lint: false
      reuse: true
    secrets:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
